### ISSUE TITLE
Org incineration conversion to engine and setup

### ISSUE THREAD

**Issue by unnitallman** [bigbinary/org_incineration#17]
Make the gem a Rails engine so that we can mount a status page on all the apps. Say at `/incineration`.  It should be a simple list page showing the details of all the organizations that have been incinerated, with the time stamp. There should be a separate tab for "Failed".  When `organization.incinerate!`  is executed, sometimes it fails. 

- We need to make sure we capture this failure and set `incineration_status` of that organization to failed. 
- Also send a custom error message to Honeybadger indicating the failure, so that we can fix the incinerator and re-rerun the incineration manually.

**Comment by unnitallman** [comment]
@shreyansh-g24 _a

**Comment by shreyansh-g24** [comment]
@unnitallman Should I create a new engine and transfer `org_incineration` code to that or convert existing app to an engine?

**Comment by shreyansh-g24** [comment]
@unnitallman _A It seems simpler to create a new engine with `rails plugin new org_incineration` and copy the `lib/` code of this gem to a service in the engine - instead of manually adding the engine setup to this gem.

-----

**Tables**
The engine will have an `organizations` table that will contain the names and timestamps of all the organizations that were attempted for incineration from the application - with some additional data like,
  - other tables that were incinerated
  - number of records incinerated for each table
  - exception raised, if any, during the incineration process
  - deleted boolean, to show success/failure

Please check if any other information needs to be captured.
We will need a new table because the original organization record will be removed from the application organizations table.

**Routes and views**
 - `/incineration` (index) for incinerated organizations
 - A similar failed (index) route for failure cases.

**And Tests** #12 

Let me know if I am missing anything.

**Comment by shreyansh-g24** [comment]
For error cases, aside from data like the exception raised and the tables shortlisted for incineration, I am not sure if any other information should be captured and saved / sent to honeybadger.

**Comment by unnitallman** [comment]
@shreyansh-g24 Let us make a new engine. The data that you are planning to capture seems alright. Go ahead with that. With Honeybadger as well, go ahead with your call.

**Comment by shreyansh-g24** [comment]
Sub-issue of #22
